### ISSUE TITLE
Package Manager Console Support

### ISSUE THREAD

**Issue by marktaling** [Augurk/Augurk#20]
From version 2.1.0 onward we will have a proper commandline tool to both upload and delete features. As this commandline tool comes in a nuget package, which you need to install in the project so you can upload anyway, it would be a logical step to be able to use this tool from the Package Manager Console.

How are we going to do this? Will we add some scripts to the CommandLine package, or add an additional package?

@jmezach Any thoughts on this?

**Comment by jmezach** [comment]
Since we already have an Augurk.CommandLine package we can simply include a PowerShell module with it to make some commands available in the Package Manager Console. Since it is then bundled with the command line tool itself in the same package it shouldn't be too hard to call the command line tool.

**Comment by marktaling** [comment]
When we chose this approach, all development went though Visual Studio. Nowadays a lot of development and feature writing is done through other tools. We will have to make new choices on which IDEs we will support and futher intrgrate with.
