### ISSUE TITLE
Split repository

### ISSUE THREAD

**Issue by marktaling** [Augurk/Augurk#43]
Now that Augurk has become an "Organization", it no longer has the limits of a single repository.

We should probably move the commandline tool to its own repository and give it a version number of its own.

**Comment by jmezach** [comment]
I started working on this, but I hit a bit of a snag because Augurk.CommandLine uses types from Augurk.Entities. I see a couple of ways to handle this:

- Create a NuGet package of Augurk.Entities and publish it to something like [MyGet](http://myget.org/opensource). They offer a free open source license for this kind of stuff.
- Make Augurk.Entities an officially supported package and publish it on NuGet.org. If we go this route however I believe it should be called something like Augurk.Client and also include some additional types so that it mimics our REST api so we can have other people integrate with it. This is similar to how [Octopus Deploy](https://www.nuget.org/packages/Octopus.Client/) does it.
- Duplicate the types from Augurk.Entities into the command line tool itself. This would mean some code duplication, but it does make the separation between the server and the client a bit more explicit.

Any preference? Or do you see any other options?

**Comment by marktaling** [comment]
Personally, I don't really resent the duplication. Nowadays code sharing between client and server on the contract level isn't guaranteed anyway. The only reason we can share it at all is because we coincidentally use the same language/platform... 
Let's just create the entities we need for the client. Who knows, maybe we want to create clients for other languages/platforms in that case we would need to do that anyway...
