### ISSUE TITLE
Onboarding experience for new developers

### ISSUE THREAD

**Issue by eNeRGy164** [Augurk/Augurk#71]
I'm new to Augurk, so I'd like some guidance/documentation on starting to develop for Augurk.
For example, what do I need to get the code building en tested on a clean machine.

As starting point, I'll add the things I encountered. Though testing still fails.
* Visual Studio 201x+ (I used 2017)
* Change bitness of IIS Express to x64 on Augurk

Where I still struggle:
* .gitignore contains a rule that should ignore SpecFlow generated code, though every feature file has one in git, except for `UML.feature`, building therefore does not work
* I propbably need the *SpecFlow for Visual Studio 201x* extension, this might solve the previous step
* Testing all Specifications are ignored, this might be on purpose, please specify
* Testing all Tests fail with `: Voron is prone to failure in 32-bits mode. Use Raven/Voron/AllowOn32Bits to force voron in 32-bit process.`, this might be on purpose, please specify

**Comment by jmezach** [comment]
@eNeRGy164 Great question. We know we have some work to do on this topic, but since we haven't had many contributions in the past we haven't spent much time on it yet. Obviously this is a chicken and egg problem, so thanks for bringing this up.

As for the missing generated code, I think that @marktaling could comment on that. We are probably missing the [SpecFlow.Tools.MsBuild.Generation](https://www.nuget.org/packages/SpecFlow.Tools.MsBuild.Generation/2.4.0) package in our project to make this work. That being said, we don't actually have any automation logic behind those features files at all right now. We're mostly using them to document the features of Augurk, but we aren't really testing them yet. It's on my todo list, but you know how it goes ;).

As for the unit tests, you should be able to run those, but you need to run them in 64-bit mode. So you'll need to switch the test platform architecture. Have a look at this [doc](https://docs.microsoft.com/en-us/visualstudio/test/run-a-unit-test-as-a-64-bit-process?view=vs-2017) for instructions on how to do this.

**Comment by jmezach** [comment]
Closing this for now. With the contribution from @eNeRGy164 we have some docs already and with the ongoing port to .NET Core this will become even easier.
